[font]
size = 12.0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 4, y = 0}
decorations = "Full"
opacity = 0.95
